---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-labserver
  labels: 
    app: labserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labserver
  template:
    metadata:
      annotations:
      labels:
        app: labserver
    spec:
      containers:
        - name: {{ .Release.Name }}-labserver
          securityContext: {}
          image: "{{ .Values.image.registry }}/{{ .Values.image.ls_repository}}:{{ .Values.image.ls_tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: "SPIRENTD_LICENSE_FILE"
              value: {{ quote .Values.license.addr }}
            - name: "IQ_SERVER_ADDR"
              value: {{ quote .Values.iq.addr }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: ssh 
              containerPort: 22 
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stc
  labels: 
    app: stc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: stc
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                { "name" : {{quote .Values.stc.test_network_name}},
                  "interfaceRequest": "eth1" }
        ]'
      labels:
        app: stc
    spec:
      containers:      
        - name: {{ .Release.Name }}-stc
          securityContext: {
            "capabilities": {
              "add": [
                "SYS_ADMIN",
                "NET_ADMIN",
                "SYS_NICE",
                "SYSLOG",
                "SYS_PTRACE",
                "SYS_RAWIO"
              ]
            }
          }
          image: "{{ .Values.image.registry }}/{{ .Values.image.stc_repository}}:{{ .Values.image.stc_tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "SPIRENT_ADMIN"
              value: "--mode container --ipv4mode container --ipv6mode container --speed 10G --driver none --benchmark True" 
          ports:
            - name: chassis-port-t
              containerPort: 40004
              protocol: TCP
            - name: chassis-port-u
              containerPort: 40004
              protocol: UDP
            - name: group-port
              containerPort: 51204
              protocol: TCP
            - name: upgrade-port
              containerPort: 1666
              protocol: TCP
            - name: rest-port
              containerPort: 9090
              protocol: TCP
          command:
            - /sbin/init
